name: Build Android APK

on:
  push:
    branches:
      - main

  workflow_dispatch:


permissions:
  contents: write


jobs:
  build:
    name: Build Android APK
    runs-on: self-hosted


    steps:

      #=========================================
      # Checkout Repository
      #=========================================
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true


      #=========================================
      # Cache Unity Library
      #=========================================
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-


      #=========================================
      # Check Unity
      #=========================================
      - name: Check Unity Installation
        shell: powershell
        run: |

          $unity = "C:\Program Files\Unity\Hub\Editor\6000.3.8f1\Editor\Unity.exe"


          if (!(Test-Path $unity)) {
              throw "Unity not found: $unity"
          }


          Write-Host "Unity Found"
          & $unity -version



      #=========================================
      # Build APK
      #=========================================
      - name: Build APK
        shell: powershell
        run: |

          $unity = "C:\Program Files\Unity\Hub\Editor\6000.3.8f1\Editor\Unity.exe"


          Write-Host "========== START UNITY BUILD =========="


          & $unity `
            -batchmode `
            -nographics `
            -projectPath "${{ github.workspace }}" `
            -executeMethod BuildScript.BuildAndroid `
            -logFile unity-build.log


          $exitCode = $LASTEXITCODE


          Write-Host ""
          Write-Host "========== UNITY EXIT CODE =========="
          Write-Host $exitCode


          Write-Host ""
          Write-Host "========== UNITY LOG =========="


          if(Test-Path unity-build.log)
          {
              Get-Content unity-build.log
          }
          else
          {
              Write-Host "Unity log not created"
          }


          exit $exitCode



      #=========================================
      # Find APK
      #=========================================
      - name: Find APK Output
        shell: powershell
        run: |

          Write-Host "========== SEARCHING APK =========="


          $apkFiles = Get-ChildItem `
            "${{ github.workspace }}" `
            -Recurse `
            -Filter *.apk


          if($apkFiles.Count -eq 0)
          {
              Write-Host "NO APK FOUND"
              exit 1
          }


          foreach($apk in $apkFiles)
          {
              Write-Host $apk.FullName
          }



      #=========================================
      # Upload APK Artifact
      #=========================================
      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:

          name: ImmuniPlay-APK

          path: |
            **/*.apk



      #=========================================
      # Upload APK To Release
      #=========================================
      - name: Upload APK To Release
        if: success()
        uses: softprops/action-gh-release@v2

        with:

          tag_name: v1.0.0

          files: |
            **/*.apk

          fail_on_unmatched_files: true


        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}